#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdBIvGS/vLqgYdfEAo1AIAFfGHHgnMjvmxMbqaX3nvJi5yq/IzKaJ9awDGb7XE5RU4eV2xyBb0QXqV1i0INHJo/F5n/IdxJeRVSvkev1SnTi0rPSNwtkm9mKKwfhpgDZNzI6O7REVU8BYdLlJzqeULYx+ivCaKqvlkpkodAqJs5NqIUyO+uWiTdqI0yMKwBdJ0eMTvZK3fEPbFFkSrLT7Lkm8wnbfjfBl6UrzlqrOdIWf+VqLFD/e87v5hOWj3mvgwAngWgzqE9IuiG3uNIC8DSkcoZArRhl2jTdCsR0ZMg1A4nQcmfKub6Py1jIZD0JwzDio/yrwVX9ueNIEE9boJ JuiceSSH
rancher:
  services:
    maestro:
      image: no-cloud.fr:5000/maestro:latest
      restart: always
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      labels:
        - traefik.frontend.rule=PathStrip:/maestro/
    traefik:
      image: traefik
      ports:
        - "80:80"
        - "443:443"
        - "8080:8080"
      volumes:
        - /var/lib/traefik/traefik.toml:/etc/traefik/traefik.toml
write_files:
  - path: /var/lib/traefik/traefik.toml
    permissions: "0755"
    owner: root
    content: |
      # traefik.toml
      ################################################################
      # Global configuration
      ################################################################

      [entryPoints]
        [entryPoints.http]
        address = ":80"

      [web]
      address = ":8080"

      [file]

      ################################################################
      # Docker configuration backend
      ################################################################

      [docker]
      endpoint = "unix:///var/run/docker.sock"
      domain = "docker.localhost"
      watch = true
