version: '2'

services:

  ldap:
    image: osixia/openldap
    container_name: ldap
    restart: always
    networks:
      ldap:
        aliases:
          - ldap
    environment:
      - LDAP_ORGANISATION=home
      - LDAP_DOMAIN=home
    volumes:
      - ldap:/var/lib/ldap
      - ldap:/etc/ldap/slapd.d

  media:
    build: media/.
    container_name: media
    volumes:
      - <my data volume>:/media

volumes:
  ldap:
    driver: local
  
networks:
  ldap:
    driver: bridge
