version: '2'

services:
  traefik:
    image: emilevauge/traefik
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
