# traefik.toml
################################################################
# Global configuration
################################################################

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "me@mydomain"
storageFile = "acme.json"
entryPoint = "https"
# caServer = "https://acme-staging.api.letsencrypt.org/directory"
[[acme.domains]]
   main = "mydomain"
   sans = [ "nextcloud.mydomain", "passbolt.mydomain", "kodi.mydomain", "jeedom.mydomain" ]

################################################################
# Docker configuration backend
################################################################

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true


